apiVersion: v1
kind: Pod 
metadata: 
  name: my-env-pod
spec: 
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers: 
  - name: ubuntu
    image: ubuntu
    env:
    - name: "AWS_PROFILE"
      value: "dop-test"
    - name: "AWS_DEFAULT_REGION"
      value: "ap-south-1"
    args:
    - "env"