apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod01
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Always
  containers:
    - name: nginx-1
      image: nginx:latest
    - name: util
      image: vinsdocker/util
      args:
      - "sleep"
      - "3600"
      
