---
apiVersion: v1
kind: Pod 
metadata: 
  name: webfront01
  labels:
    application: testapp
    tier: frontend
    az: "1"
    team: team-a
spec:
  containers:
    - name: webfront-nginx01
      image: nginx:alpine

---

apiVersion: v1
kind: Pod 
metadata: 
  name: webfront02
  labels:
    application: testapp
    tier: frontend
    az: "2"
    team: team-b
spec:
  containers:
    - name: webfront-nginx02
      image: nginx:alpine

---

apiVersion: v1
kind: Pod 
metadata: 
  name: webfront03
  labels:
    application: testapp
    tier: frontend
    az: "3"
    team: team-a
spec:
  containers:
    - name: webfront-nginx03
      image: nginx:alpine