apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-exs
spec:
  selector:
    matchLabels:
      team: team-a
  replicas: 2
  template:
    metadata:
      labels:
        team: team-a
    spec:
      containers:
        - name: nginx
          image: nginx