apiVersion: apps/v1

kind: Deployment

metadata: 
  name: position-simulator

spec:
  replicas: 1

  #minReadySeconds: 5

  selector:
    matchLabels:
      app: position-simulator

  template:
    metadata: 
      labels: 
        app: position-simulator

    spec:
      containers:
        - name: position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

