apiVersion: apps/v1

kind: Deployment

metadata: 
  name: queue

spec:
  replicas: 1

  #minReadySeconds: 5

  selector:
    matchLabels:
      app: queue

  template:
    metadata: 
      labels: 
        app: queue

    spec:
      containers:
        - name: shalabs-queue
          image: richardchesterwood/k8s-fleetman-queue:release2