apiVersion: v1
kind: Service
metadata:
  name: argo-server-np
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
      nodePort: 30024