apiVersion: v1
kind: Pod 
metadata:
  name: my-pod-grace
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      args:
        - "sleep"
        - "3600"
  restartPolicy: Never
  terminationGracePeriodSeconds: 1