apiVersion: v1
kind: Pod
metadata:
  name: nginx-shalabs
  labels:
    app: nginx-shalabs
    tier: frontend
spec:
  containers:
    - name: nginx-shalabs
      image: nginx:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      


