apiVersion: v1
kind: Pod
metadata:
  name: shalabs-nginx-webfrnt
  namespace: default
  labels:
    app: shalabs-nginx-webfrnt
    tier: frontend
spec:
  containers:
  - name: shalabs-nginx-webfrnt
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always