apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redisdb
spec:
  selector:
    matchLabels:
      app: redisdb
  replicas: 1
  template:
    metadata:
      labels: 
        app: redisdb
    spec:
      containers:
        - name: redis
          image: redis:6 
          ports:
            - name: "db-port"
              containerPort: 6379