apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-deploy-01
spec:
  selector: 
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: vinsdocker/nginx-gke
          ports:
            - name: "app-port"
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sha-web
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Pod 
metadata: 
  name: demo-pod
spec:
  containers:
    - name: demo 
      image: vinsdocker/util
      args:
       - "sleep"
       - "3600"
  terminationGracePeriodSeconds: 1
