apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sha-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: vinsdocker/nginx-gke
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: sha-srv
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001