name: 03 - Using Custom Actions
run-name: 03 - Using Custom Actions
on: push

jobs:
  node-20-release:
    runs-on: ubuntu-latest
    defaults:
     run:
        working-directory: 04-using-actions/react-app

    steps: 
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Print the folders
       run: ls -lrt

     - name: Setup Node
       uses: actions/setup-node@v3
       with:
        node-version: '20.x'

     - name: Install dependencies
       run: npm ci

     - name: Run unit tests
       run: npm run test
    
     
       